<?xml version ='1.0' encoding ='utf-8' ?>

<definitions name='ImagenesServer' 
             targetNamespace='http://expvirtual.dti.pjedomex.gob.mx/electronico/webservice/servidor/' 
             xmlns:tns='http://expvirtual.dti.pjedomex.gob.mx/electronico/webservice/servidor/' 
             xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' 
             xmlns='http://schemas.xmlsoap.org/wsdl/'> 

    <message name='ServiceAutorizaPersonasRequest'>
        <part name="jsonRequest" type="xsd:string"/>     
        <part name="usuario" type="xsd:string"/>    
        <part name="passwd" type="xsd:string"/> 
    </message> 
    
   
    <message name='ServiceAutorizaPersonasResponse'>          
        <part name='jsonResponse' type='xsd:string'/> 
    </message>                                   
      
     
    <portType name='ScramblePortType'>           
        <operation name='ServiceAutorizaPersonas'>
            <input message='tns:ServiceAutorizaPersonasRequest'/> 
            <output message='tns:ServiceAutorizaPersonasResponse'/>   
        </operation>      
    </portType>                                  

    <binding name='ScrambleBinding' type='tns:ScramblePortType'> 
        <soap:binding style='rpc' 
                      transport='http://schemas.xmlsoap.org/soap/http'/> 
        <operation name='ServiceAutorizaPersonas'> 
            <soap:operation soapAction='urn:localhost-scramble#ServiceAutorizaPersonas'/> 
            <input> 
                <soap:body use='encoded' namespace='urn:localhost-scramble' 
                           encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/> 
            </input> 
            <output> 
                <soap:body use='encoded' namespace='urn:localhost-scramble' 
                           encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/> 
            </output> 
        </operation>       
    </binding> 

    <service name='ScrambleService'> 
        <port name='ScramblePort' binding='ScrambleBinding'> 
            <soap:address location='http://expvirtual.dti.pjedomex.gob.mx/electronico/webservice/servidor/autorizapersonas/AutorizaPersonasServer.php?wsdl'/> 
        </port> 
    </service>
</definitions> 
